---
# tasks file for loadbalancer
- name: Install HAProxy
  package: 
    name: "haproxy" 
    state: present 

- name: Configure HAProxy
  template: 
    src: "haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
  notify: restart haproxy 

- name: Start haproxy service
  service:
    name: "haproxy"
    state: started  

